# Ejercicios de Repaso

## Ejercicios Pandas y Numpy

In [25]:
import pandas as pd
import numpy as np

### 1. Obtener la versión de la librería pandas.

In [26]:
pd.__version__

'2.2.2'

### 2. Crear y visualizar una serie unidimensional como una estructura Series. Realiza .size y .describe()

In [27]:
x = pd.Series([1, 2, 3])

print(x.size)
print("-------------")
print(x.describe())

3
-------------
count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

### 3. Convertir un objeto Series a una lista Python.

In [28]:
lista_python = x.tolist()
print(lista_python)

[1, 2, 3]

### 4. Aplicar las operaciones aritméticas básicas sobre objetos Series.

Operación,Operador,Método de Series

*   Suma,+,".add(other, fill_value=None)"
*   Resta,-,".sub(other, fill_value=None)"
*   Multiplicación,*,".mul(other, fill_value=None)"
*   División,/,".div(other, fill_value=None)":

In [29]:
serie_a = pd.Series([10, 20, 30])
serie_b = pd.Series([5, 10, 15])

serie_suma = serie_a.add(serie_b)
serie_resta = serie_a.sub(serie_b)
serie_multiplicacion = serie_a.mul(serie_b)
serie_division = serie_a.div(serie_b)

In [30]:
print(serie_suma)
print("-------------")
print(serie_resta)
print("-------------")
print(serie_multiplicacion)
print("-------------")
print(serie_division)

0    15
1    30
2    45
dtype: int64
-------------
0     5
1    10
2    15
dtype: int64
-------------
0     50
1    200
2    450
dtype: int64
-------------
0    2.0
1    2.0
2    2.0
dtype: float64

### 5. Usar operadores relacionales para comparar objetos Series. (==, >, <)

Operador,Método de Series,Descripción

*   "==,.eq(),Igual a"
*   "!=,.ne(),No igual a"
*   ">,.gt(),Mayor que"
*   "<,.lt(),Menor que"
*   ">=,.ge(),Mayor o igual que"
*   <=,.le(),Menor o igual que

In [31]:
serie_ventas = pd.Series([300, 200, 300], index=['Ene', 'Feb', 'Mar'])
serie_meta = pd.Series([150, 200, 450], index=['Ene', 'Feb', 'Mar'])

In [32]:
print(serie_ventas.eq(serie_meta))
print("-------------")
print(serie_ventas.ne(serie_meta))
print("-------------")
print(serie_ventas.gt(serie_meta))
print("-------------")
print(serie_ventas.lt(serie_meta))
print("-------------")
print(serie_ventas.ge(serie_meta))
print("-------------")
print(serie_ventas.le(serie_meta))

Ene    False
Feb     True
Mar    False
dtype: bool
-------------
Ene     True
Feb    False
Mar     True
dtype: bool
-------------
Ene     True
Feb    False
Mar    False
dtype: bool
-------------
Ene    False
Feb    False
Mar     True
dtype: bool
-------------
Ene     True
Feb     True
Mar    False
dtype: bool
-------------
Ene    False
Feb     True
Mar     True
dtype: bool

### 6. Convertir un diccionario Python en un objeto Series.

In [33]:
diccionario_poblacion = {
    'España': 47.6,
    'Francia': 67.8,
    'Alemania': 83.2,
    'Italia': 59.1
}

print("--- Diccionario Python ---")
print(type(diccionario_poblacion))
print(diccionario_poblacion)


# 2. Convertir el diccionario a Series
series_poblacion = pd.Series(diccionario_poblacion)

print("\n--- Objeto Pandas Series ---")
print(type(series_poblacion))
print(series_poblacion)

--- Diccionario Python ---
<class 'dict'>
{'España': 47.6, 'Francia': 67.8, 'Alemania': 83.2, 'Italia': 59.1}

--- Objeto Pandas Series ---
<class 'pandas.core.series.Series'>
España      47.6
Francia     67.8
Alemania    83.2
Italia      59.1
dtype: float64

### 7. Convertir un array NumPy en un objeto Series.

In [34]:
array_temperaturas = np.array([25, 28, 22, 26, 20])

print("--- Array NumPy ---")
print(type(array_temperaturas))
print(array_temperaturas)


# 2. Convertir el array a Series
# Por defecto, Pandas asignará un índice entero (0, 1, 2, ...)
series_temperaturas = pd.Series(array_temperaturas)

print("\n--- Objeto Pandas Series Resultante (Índice por defecto) ---")
print(type(series_temperaturas))
print(series_temperaturas)

# 3. Conversión especificando un Índice
# También puedes proporcionar etiquetas personalizadas para el índice.
dias = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie']
series_con_indice = pd.Series(array_temperaturas, index=dias)

print("\n--- Objeto Pandas Series (Índice Personalizado) ---")
print(series_con_indice)

--- Array NumPy ---
<class 'numpy.ndarray'>
[25 28 22 26 20]

--- Objeto Pandas Series Resultante (Índice por defecto) ---
<class 'pandas.core.series.Series'>
0    25
1    28
2    22
3    26
4    20
dtype: int64

--- Objeto Pandas Series (Índice Personalizado) ---
Lun    25
Mar    28
Mié    22
Jue    26
Vie    20
dtype: int64

### 8. Cambiar el tipo de datos de un objeto Series. to_numeric

In [35]:
s = pd.Series(['100', '200', 'python', '300.5'])

# 'coerce' convierte los errores (texto no numérico) en NaN
s_numerica = pd.to_numeric(s, errors='coerce')

print(s_numerica)

0    100.0
1    200.0
2      NaN
3    300.5
dtype: float64

### 9. Extraer una fila de un DataFrame como un objeto Series.

In [36]:
datos = {'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]}
df = pd.DataFrame(datos)

# Extraer la primera fila (índice 0)
fila = df.iloc[0]

print(fila)
print(type(fila))

A    1
B    4
C    7
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>

### 10. Convertir un objeto Series con múltiples listas en un único objeto Series.

In [37]:
datos = {'A': [1, 2, 3, 4, 5], 'B': [6, 5, 4, 3, 2], 'C': [2, 3, 5, 7, 11]}

df = pd.DataFrame(data=datos)

df

   A  B   C
0  1  6   2
1  2  5   3
2  3  4   5
3  4  3   7
4  5  2  11

In [38]:
fila = df.iloc[2,:]

print(fila)
print(type(fila))

A    3
B    4
C    5
Name: 2, dtype: int64
<class 'pandas.core.series.Series'>

### 11. Ordenar los valores de un objeto Series con el método sort_values.

In [39]:
s = pd.Series(['z', 'a', 'm', 'b'])

s_ordenada = s.sort_values()

print(s_ordenada)

1    a
3    b
2    m
0    z
dtype: object

### 12. Agregar datos a un objeto Series existente.

In [40]:
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

# .append() fue eliminado en pandas 2.0, se usa concat
nueva_s = pd.concat([s1, s2], ignore_index=True)

print(nueva_s)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

### 13. Crear un objeto Series a partir de un filtro aplicado a otro objeto Series.

In [41]:
s = pd.Series([1, 5, 10, 15, 20])

# Filtro: Valores mayores a 10
s_filtrada = s[s > 10]

print(s_filtrada)

3    15
4    20
dtype: int64

### 14. Cambiar el orden del índice de un objeto Series.

In [42]:
s = pd.Series(data=[1, 2, 3, 4], index=['A', 'B', 'C', 'D'])

# Reordenar índices
s_reordenada = s.reindex(['D', 'C', 'B', 'A'])

print(s_reordenada)

D    4
C    3
B    2
A    1
dtype: int64

### 15. Obtener la desviación estándar y el promedio de un conjunto de datos de una serie.

In [43]:
s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Promedio (mean):", s.mean())
print("Desviación Estándar (std):", s.std())

Promedio (mean): 5.0
Desviación Estándar (std): 2.7386127875258306

### 16. Calcular los valores mínimo y máximo de un objeto Series.

In [44]:
s = pd.Series([5, 1, 9, 3, 7])

print("Mínimo:", s.min())
print("Máximo:", s.max())

Mínimo: 1
Máximo: 9

### 17. Obtener estadísticas básicas de un objeto Series con el método describe.

In [45]:
s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Muestra count, mean, std, min, max, y cuartiles
print(s.describe())

count    10.00000
mean      5.50000
std       3.02765
min       1.00000
25%       3.25000
50%       5.50000
75%       7.75000
max      10.00000
dtype: float64

### 18. Obtener los elementos pares e impares de un objeto Series numérico.

In [46]:
s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8])

pares = s[s % 2 == 0]
impares = s[s % 2 != 0]

print("Pares:\n", pares)
print("Impares:\n", impares)

Pares:
 1    2
3    4
5    6
7    8
dtype: int64
Impares:
 0    1
2    3
4    5
6    7
dtype: int64

### 19. Eliminar los valores NaN de una serie con el método dropna.

In [47]:
s = pd.Series([1, np.nan, 3, np.nan, 5])

s_limpia = s.dropna()

print(s_limpia)

0    1.0
2    3.0
4    5.0
dtype: float64

### 20. Calcular el valor absoluto de los elementos de un objeto Series.

In [48]:
s = pd.Series([-5, 10, -15, 20, -25])

s_abs = s.abs()

print(s_abs)

0     5
1    10
2    15
3    20
4    25
dtype: int64

### 21. Reemplazar por un valor arbitrario los valores de una serie que no satisfagan una condición.

In [49]:
s = pd.Series([10, 20, 30, 40, 50])

# Conservar valores > 25, el resto reemplazarlos por -1
# .where mantiene los que cumplen la condición, reemplaza los que NO
s_modificada = s.where(s > 25, -1)

print(s_modificada)

0    -1
1    -1
2    30
3    40
4    50
dtype: int64

## Ejercicios DataSet

In [50]:
import pandas as pd
import numpy as np

nombre = ['Oliva', 'Daniela', 'Juan', 'Germán', 'Edward', 'Alex', 'Julio',
          'Edgar', 'Angie', 'Irlesa']
puntaje = [11.5, 8, 15.5, np.nan, 8, 19, 13.5, np.nan, 8, 18]
intentos = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
califico = ['Sí', 'No', 'Sí', 'No', 'No', 'Sí', 'Sí', 'No', 'No', 'Sí']

indices = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

jugadores = {'nombre': nombre, 'puntaje': puntaje, 'intentos': intentos,
             'califico': califico}

df = pd.DataFrame(data=jugadores, index=indices)

df

    nombre  puntaje  intentos califico
a    Oliva     11.5         1       Sí
b  Daniela      8.0         3       No
c     Juan     15.5         2       Sí
d   Germán      NaN         3       No
e   Edward      8.0         2       No
f     Alex     19.0         3       Sí
g    Julio     13.5         1       Sí
h    Edgar      NaN         1       No
i    Angie      8.0         2       No
j   Irlesa     18.0         1       Sí


### 1. Obtener las primeras 3 filas de un objeto DataFrame.

In [51]:
df.head(3)

    nombre  puntaje  intentos califico
a    Oliva     11.5         1       Sí
b  Daniela      8.0         3       No
c     Juan     15.5         2       Sí


### 2. Obtener las últimas 3 filas de un objeto DataFrame.

In [52]:
df.tail(3)

   nombre  puntaje  intentos califico
h   Edgar      NaN         1       No
i   Angie      8.0         2       No
j  Irlesa     18.0         1       Sí

### 3. Seleccionar columnas de un objeto DataFrame usando notación de slicing (iloc).

In [53]:
# Seleccionamos todas las filas, y las columnas de la posición 0 a la 2 (exclusivo)
slice_cols = df.iloc[:, 0:2]
print(slice_cols)

    nombre  puntaje
a    Oliva     11.5
b  Daniela      8.0
c     Juan     15.5
d   Germán      NaN
e   Edward      8.0
f     Alex     19.0
g    Julio     13.5
h    Edgar      NaN
i    Angie      8.0
j   Irlesa     18.0

### 4. Obtener la representación en NumPy de un objeto DataFrame.

In [54]:
array_numpy = df.to_numpy()
# O también: df.values
print(array_numpy)

[['Oliva' 11.5 1 'Sí']
 ['Daniela' 8.0 3 'No']
 ['Juan' 15.5 2 'Sí']
 ['Germán' nan 3 'No']
 ['Edward' 8.0 2 'No']
 ['Alex' 19.0 3 'Sí']
 ['Julio' 13.5 1 'Sí']
 ['Edgar' nan 1 'No']
 ['Angie' 8.0 2 'No']
 ['Irlesa' 18.0 1 'Sí']]


### 5. Seleccionar columnas de un objeto DataFrame usando notación de slicing (loc).

In [55]:
# Slicing usando nombres de columnas (inclusivo en ambos extremos)
slice_loc = df.loc[:, 'nombre':'intentos']
print(slice_loc)

    nombre  puntaje  intentos
a    Oliva     11.5         1
b  Daniela      8.0         3
c     Juan     15.5         2
d   Germán      NaN         3
e   Edward      8.0         2
f     Alex     19.0         3
g    Julio     13.5         1
h    Edgar      NaN         1
i    Angie      8.0         2
j   Irlesa     18.0         1


### 6. Obtener los ejes (atributos de filas y columnas) de un DataFrame.

In [56]:
print("Ejes del DataFrame:", df.axes)
print("Índices (filas):", df.index)
print("Columnas:", df.columns)

Ejes del DataFrame: [Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object'), Index(['nombre', 'puntaje', 'intentos', 'califico'], dtype='object')]
Índices (filas): Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')
Columnas: Index(['nombre', 'puntaje', 'intentos', 'califico'], dtype='object')

### 7. Seleccionar filas y columnas específicas de un DataFrame con iloc.

In [57]:
# Filas en índices 1 y 3, Columnas en índices 0 y 2
seleccion = df.iloc[[1, 3], [0, 2]]
print(seleccion)

    nombre  intentos
b  Daniela         3
d   Germán         3


### 8. Obtener la dimensión, el tamaño, y la forma de un objeto DataFrame.

In [58]:
print("Dimensión (ndim):", df.ndim)
print("Tamaño (size - total elementos):", df.size)
print("Forma (shape - filas, cols):", df.shape)

Dimensión (ndim): 2
Tamaño (size - total elementos): 40
Forma (shape - filas, cols): (10, 4)


### 9. Obtener la cantidad de memoria ocupada por cada columna en un DataFrame.

In [59]:
print(df.memory_usage())

Index       380
nombre       80
puntaje      80
intentos     80
califico     80
dtype: int64

### 10. Seleccionar los registros que tienen un campo nulo (nan).

In [60]:
# Filtramos filas donde 'puntaje' es nulo
nulos = df[df['puntaje'].isnull()]
print(nulos)

   nombre  puntaje  intentos califico
d  Germán      NaN         3       No
h   Edgar      NaN         1       No

### 11. Modificar un valor o entrada específico de un objeto DataFrame usando loc.

In [61]:
# Modificamos el puntaje del índice 'd' que era NaN a 10.0
df.loc['d', 'puntaje'] = 10.0
print(df.loc['d'])

nombre      Germán
puntaje       10.0
intentos         3
califico        No
Name: d, dtype: object


### 12. Sumar los valores de una columna de un DataFrame con sum.

In [62]:
suma_intentos = df['intentos'].sum()
print("Total de intentos:", suma_intentos)

Total de intentos: 19

### 13. Calcular el promedio de los valores de una columna de un DataFrame.

In [63]:
promedio_puntaje = df['puntaje'].mean()
print("Promedio de puntaje:", promedio_puntaje)

Promedio de puntaje: 12.38888888888889


### 14. Insertar una nueva columna en una posición arbitraria con la función insert.

In [64]:
# Insertamos columna 'nivel' en la posición 4
if 'nivel' not in df.columns:
    niveles = ['A', 'B', 'A', 'C', 'B', 'A', 'A', 'C', 'C', 'A']
    df.insert(4, 'nivel', niveles)
    print(df.head())

    nombre  puntaje  intentos califico nivel
a    Oliva     11.5         1       Sí     A
b  Daniela      8.0         3       No     B
c     Juan     15.5         2       Sí     A
d   Germán     10.0         3       No     C
e   Edward      8.0         2       No     B


### 15. Eliminar una fila de un DataFrame con la función drop.

In [65]:
# Eliminamos la fila con índice 'h'.
# Usamos un nuevo DF para no perder datos para los siguientes ejercicios.
df_dropped = df.drop('h')
print(df_dropped.tail())

   nombre  puntaje  intentos califico nivel
e  Edward      8.0         2       No     B
f    Alex     19.0         3       Sí     A
g   Julio     13.5         1       Sí     A
i   Angie      8.0         2       No     C
j  Irlesa     18.0         1       Sí     A

### 16. Ordenar en modo descendente un DataFrame por diferentes columnas.

In [67]:
# Ordena por 'puntaje' (descendente: de mayor a menor) y luego por 'intentos'
# (ascendente: de menor a mayor) como criterio de desempate.
ordenado = df.sort_values(by=['puntaje', 'intentos'], ascending=[False, True])
print(ordenado)

    nombre  puntaje  intentos califico nivel
f     Alex     19.0         3       Sí     A
j   Irlesa     18.0         1       Sí     A
c     Juan     15.5         2       Sí     A
g    Julio     13.5         1       Sí     A
a    Oliva     11.5         1       Sí     A
d   Germán     10.0         3       No     C
e   Edward      8.0         2       No     B
i    Angie      8.0         2       No     C
b  Daniela      8.0         3       No     B
h    Edgar      NaN         1       No     C

### 17. Usar la función mask para modificar los valores que cumplan una condición.

In [68]:
# Reemplazar con 0 los puntajes menores a 10
# Mask reemplaza donde la condición es VERDADERA
df_masked = df.mask(df['puntaje'] < 10, 0)
print(df_masked)

   nombre  puntaje  intentos califico nivel
a   Oliva     11.5         1       Sí     A
b       0      0.0         0        0     0
c    Juan     15.5         2       Sí     A
d  Germán     10.0         3       No     C
e       0      0.0         0        0     0
f    Alex     19.0         3       Sí     A
g   Julio     13.5         1       Sí     A
h   Edgar      NaN         1       No     C
i       0      0.0         0        0     0
j  Irlesa     18.0         1       Sí     A

### 18. Realizar consultas sobre los elementos de un objeto DataFrame con la función query.

In [69]:
# Consultar jugadores con más de 1 intento y puntaje mayor a 10
resultado = df.query('intentos > 1 and puntaje > 10')
print(resultado)

  nombre  puntaje  intentos califico nivel
c   Juan     15.5         2       Sí     A
f   Alex     19.0         3       Sí     A

### 19. Guardar los registros de un DataFrame en un archivo de formato CSV.

In [70]:
df.to_csv('jugadores.csv')
print("Archivo guardado. Revisa la carpeta de archivos de Colab.")

Archivo guardado. Revisa la carpeta de archivos de Colab.